steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'beta',
    'run',
    'deploy',
    '--allow-unauthenticated',
    '${_CLOUD_RUN_SERVICE}',
    '--image',
    'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}',
    '--region',
    'us-central1',
    '--platform',
    'managed',
    '--memory',
    '128Mi',
    '--update-env-vars',
    'APP_DEBUG=${_APP_DEBUG},
    APP_KEY=${_APP_KEY},
    APP_NAME=${_APP_NAME},
    APP_ENV=${_APP_ENV},
    APP_ENCODING=UTF-8,
    APP_DEFAULT_LOCALE=en_US,
    APP_DEFAULT_TIMEZONE=UTC,
    DB_CONNECTION=${_DB_CONNECTION},
    DB_HOST=${_DB_HOST},
    DB_DATABASE=${_DB_DATABASE},
    DB_USERNAME=${_DB_USERNAME},
    DB_PASSWORD=${_DB_PASSWORD},
    GOOGLE_CLOUD_PROJECT=${PROJECT_ID},
    FIRESTORE_PROJECT_ID=${_FIRESTORE_PROJECT_ID},
    FIRESTORE_WEB_API_KEY=${_FIRESTORE_WEB_API_KEY}'
    ]
images:
- gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}

options:
    substitution_option: 'ALLOW_LOOSE'

substitutions:
    _APP_DEBUG: 'true'
    _APP_ENV: local
    _APP_KEY: ''
    _APP_NAME: ''
    _DB_CONNECTION: 'pgsql'
    _DB_DATABASE: ''
    _DB_HOST: ''
    _DB_PORT: '5432'
    _DB_USERNAME: ''
    _DB_PASSWORD: ''
    _CLOUD_RUN_SERVICE: 'master'
    _FIRESTORE_PROJECT_ID: ''
    _FIRESTORE_WEB_API_KEY: ''